version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - 4222
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]

  observer:
    image
  
  requirements:
    image: python:3.7-alpine
    volumes:
      - requirements:/usr/local/lib/python3.7/site-packages
      - .:/project
    working_dir: /project
    command: pip install -r requirements.txt
networks:
  nats:
    name: nats
volumes:
  images: {}
  requirements: {}