version: "3.7"
services:

  rabbitmq-message:
    container_name: message_broker
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

  download:
    build: download/.
    volumes:
      - ./images:/images
  notebook:
    image: jupyter/datascience-notebook
    #Paramètres du port("Hôte: Container")
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - .:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''

  data:
    image: python:3.7
    volumes:
      - requirements:/usr/local/lib/python3.7/site-packages
      - .:/project
    working_dir: /project
    command: python3 __data.py
    depends_on:
      - requirements


networks:
  nats:
    external:
      name: nats

volumes:
  images: {}
  requirements: {}
  # metadata:
  #   image: python:3.7
  #   volumes:
  #     - requirements:/usr/local/lib/python3.7/site-packages
  #     - __metadata.py:/project
  #   working_dir: /project
  #   command: python3 __metadata.py
  #   depends_on:
  #     - requirements
  # recommandation:
  #   image: python:3.7
  #   volumes:
  #     - requirements:/usr/local/lib/python3.7/site-packages
  #     - __recommandation.py:/project
  #   working_dir: /project
  #   command: python3 __recommandation.py
  #   depends_on:
  #     - requirements
  # stats:
  #   image: python:3.7
  #   volumes:
  #     - requirements:/usr/local/lib/python3.7/site-packages
  #     - __stats.py:/project
  #   working_dir: /project
  #   command: python3 __stats.py
  #   depends_on:
  #     - requirements
  # users_preferences:
  #   image: python:3.7
  #   volumes:
  #     - requirements:/usr/local/lib/python3.7/site-packages
  #     - __users_preferences.py:/project
  #   working_dir: /project
  #   command: python3 __users_preferences.py
  #   depends_on:
  #     - requirements
  # events:
  #   image: python:3.7
  #   volumes:
  #     - requirements:/usr/local/lib/python3.7/site-packages
  #     - __events.py:/project
  #   working_dir: /project
  #   command: python3 __events.py
  #   depends_on:
  #     - requirements
